name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    strategy:
      max-parallel: 1
      matrix:
        node: [18, 20, 22]
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        GH: ${{ secrets.GH_TOKEN }}
        DEBUG: pub:src-github
